version: "3.9"

services:
  nettleship-net-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nettleship-net-api:latest
    networks:
      - internal
      - traefik
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  traefik:
    external: true
